### ISSUE TITLE
Access to /tmp directory

### ISSUE THREAD

**Issue by zlatin** [Arnatious/qbittorrent-snap#1]
It would be nice to have access to `/tmp` directory for opening torrents directly from firefox. Now I have to save `.torrent` file  to downloads and then open it with qBittorrent.

**Comment by Arnatious** [comment]
Accessing `/tmp` an open problem in `snapd` at the moment,  https://forum.snapcraft.io/t/sharing-files-via-tmp/1613/16

The gist is that the `/tmp` firefox is seeing is specific to its mount namespace.

A fix is in the pipeline for Firefox 77, which will make Firefox use `$HOME/Downloads/firefox.tmp` instead of `/tmp` for opened files. It'll also improve file handling in general.
